### ISSUE TITLE
視点移動機能 Viewpoint Movement feature

### ISSUE THREAD

**Issue by cormojs** [billhung/GGJ2020#1]

**Comment by billhung** [comment]
参考ビデオ: https://www.youtube.com/watch?v=HIyxpl-Yahs

**Comment by billhung** [comment]
First Person Controller導入手順
http://www.sugawara.ac.jp/digital/blog/gamecg-unity-semi/unity-1stscene-03

**Comment by billhung** [comment]
Dissolve表現処理、GITにCOMMITしました：
https://github.com/billhung/GGJ2020/commit/29e91d73c3066262c0537660a367f62790a13f87

**Comment by billhung** [comment]
確認できました。ありがとうございます。
https://github.com/billhung/GGJ2020/commit/7363b60be865a1edd15ac1cabf4f3993d9a9362e
