### ISSUE TITLE
Fire effect 炎エフェクト

### ISSUE THREAD

**Issue by billhung** [billhung/GGJ2020#13]
参考
![ShuriCastleFile](https://user-images.githubusercontent.com/2110915/73602058-63413580-45b0-11ea-8af8-741e29a858c5.JPG)

**Comment by RRem133** [comment]
[PS_FireMain.zip](https://github.com/billhung/GGJ2020/files/4143556/PS_FireMain.zip)

**Comment by RRem133** [comment]
[FireMatsPackage.zip](https://github.com/billhung/GGJ2020/files/4143572/FireMatsPackage.zip)

**Comment by RRem133** [comment]
[ShurCastle_Broken.zip](https://github.com/billhung/GGJ2020/files/4143636/ShurCastle_Broken.zip)

**Comment by billhung** [comment]
Thanks
