### ISSUE TITLE
修理城の3Dモデル Shuri Castle 3D model

### ISSUE THREAD

**Issue by cormojs** [billhung/GGJ2020#2]

**Comment by RRem133** [comment]
[Shuri.zip](https://github.com/billhung/GGJ2020/files/4142124/Shuri.zip)

**Comment by RRem133** [comment]
[ShuriCastle_Incomplete1PM.zip](https://github.com/billhung/GGJ2020/files/4142138/ShuriCastle_Incomplete1PM.zip)

**Comment by RRem133** [comment]
[ShuriCastle_Incomplete5PM.zip](https://github.com/billhung/GGJ2020/files/4142299/ShuriCastle_Incomplete5PM.zip)

**Comment by RRem133** [comment]
[ShuriCastle_IncomParts7PM.zip](https://github.com/billhung/GGJ2020/files/4142388/ShuriCastle_IncomParts7PM.zip)

**Comment by RRem133** [comment]
[ShuriFloor.zip](https://github.com/billhung/GGJ2020/files/4142455/ShuriFloor.zip)

**Comment by billhung** [comment]
yesterday 7pm's model will be the final submission version according to @Reapist 
昨日７PMのモデルは最終の提出バージョン、@Reapistと確認済み。
